name: Build and Deploy client and server Dockerfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy-server:
    name: Build and Deploy server
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Prepare
      id: prepare
      run: |
       DOCKER_IMAGE= marksman007/moviemanor-server
       echo ::set-output name=docker_image::${DOCKER_IMAGE}
                    
    - name: Build and push Server image
      uses: docker/build-push-action@v3
      with:
       push: true
       context: ./server
       tags: latest
       
#   build-and-deploy-client:
#     name: Build and Deploy client
#     runs-on: ubuntu-latest
#     steps: 
#     - name: Checkout code
#       uses: actions/checkout@v3
      
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2
      
#     - name: Build and push client image
#       uses: docker/build-push-action@v3
#       with: 
#        image: moviemanor-client
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        context: .
#        dockerfile: client/Dockerfile
#        tags: latest
