name: Build and Push Client and Server
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        context: ./server
    
    - name: Build the Docker image
      run: docker build . --tag moviemanor-server --file server/Dockerfile
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     
    - name: Tags
      run: docker tag moviemanor-server marksman007/moviemanor-server
    
    - name: Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/moviemanor-server
      
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        context: ./client
    
    - name: Build the Docker image
      run: docker build . --tag moviemanor-client --file client/Dockerfile
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     
    - name: Tags
      run: docker tag moviemanor-client marksman007/moviemanor-client
    
    - name: Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/moviemanor-client
