name: Build and Deploy client and server Dockerfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy-server:
    name: Build and Deploy server
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build and push Server image
      uses: docker/build-push-action@v3
      with: 
       image: moviemanor-server
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       context: .
       dockerfile: server/Dockerfile
       tags: latest
       
  build-and-deploy-client:
    name: Build and Deploy client
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build and push client image
      uses: docker/build-push-action@v3
      with: 
       image: moviemanor-client
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       context: .
       dockerfile: client/Dockerfile
       tags: latest
