name: Build and Deploy client and server Dockerfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy-server:
    name: Build and Deploy server
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          marksman007/moviemanor-server      
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
                      
    - name: Build and push Server image
      uses: docker/build-push-action@v3
      with:
       context: ./server
       push: true
       tags: moviemanor-server
       
#   build-and-deploy-client:
#     name: Build and Deploy client
#     runs-on: ubuntu-latest
#     steps: 
#     - name: Checkout code
#       uses: actions/checkout@v3
    
#     - name: Docker meta
#       id: meta
#       uses: docker/metadata-action@v3
#       with:
#         # list of Docker images to use as base name for tags
#         images: |
#           marksman007/moviemanor-client      
        
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2
      
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
    
#     - name: Login to DockerHub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
                      
#     - name: Build and push Client image
#       uses: docker/build-push-action@v3
#       with:
#        context: .
#        file: client/Dockerfile
#        push: true
#        tags: latest
