name: Build and Push Client and Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        context: ./server
    - name: Build the Docker image
      run: docker build --tag moviemanor-server:$(date +%s) --file server/Dockerfile
